apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: roboshop
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-076246491afad5bb5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: roboshop
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: test-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: roboshop
  labels:
    purpose: volumes 
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
---
apiVersion: v1 
kind: Service
metadata:
  name: ebs-svc
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: volumes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
