apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: roboshop
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-06184e8b1e70c6007

