apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    Project: roboshop
    environment: dev
  namespace: roboshop
spec:
  containers:
  - name: almalinux
    image: almalinux
    command: ["sleep","1000"]