apiVersion: v1
kind: Pod
metadata:
  name: env 
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: DevSecOps
    - name: Trainer
      value: ShivaKumar