apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom: # base64 encoded values are decoded and attached as env for container
    - secretRef:
        name: secret-demo