apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    Project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # this can be 80 as default service port or we can give any other
    targetPort: 80 # containerport