apiVersion: v1
kind: Pod
metadata:
  name: pod-service
  labels:
    Project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerport: 80