apiVersion: v1
kind: Pod
metadata:
  name: nginx-np-pod
  labels:
    Project: roboshop
    component: frontend
    environment: dev
    purpose: NodePort
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80