apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
spec:
  type: LoadBalancer
  selectors:
    Project: roboshop
    component: frontend
    environment: dev
    purpose: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodeport: 30007