apiVersion: v1 
kind: Service
metadata:
  name: ss-svc
spec:
  selector:
    Project: roboshop
    environment: dev
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
---
apiVersion: v1 
kind: Service
metadata:
  name: ss-headless
spec:
  clusterIP: None 
  selector:
    Project: roboshop
    environment: dev
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-demo
  labels: 
    Project: roboshop
    environment: dev
spec:
  selector:
    matchLabels:
      Project: roboshop
      environment: dev
  serviceName: "ss-headless" #headless service name
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        Project: roboshop
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi